FROM registry.cn-shanghai.aliyuncs.com/russell-hub/dl-base:1.1.0-gpu-py2.9
MAINTAINER RussellCloud Labs

ARG CHAINER_VERSION=2.0.0

RUN pip --no-cache-dir install --upgrade chainer==${CHAINER_VERSION}